dataset_name: default
dataset_path: TheFinAI/JFTE
output_type: generate_until
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
fewshot_split: test
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "@@"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 256

metric_list:
  - metric: term_hr
    aggregation: !function jp_utils.term_hr_agg
    higher_is_better: true

  - metric: term_max_f1
    aggregation: !function jp_utils.term_max_f1_agg
    higher_is_better: true

metadata:
  version: '1.0'
task: JFTE
tag: jp
test_split: test
process_results: !function jp_utils.process_results
